spring.application.name=course-tracker
server.port=8080

spring.datasource.url=jdbc:h2:mem:coursetracker;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false

springdoc.swagger-ui.path=/swagger-ui.html
